import type { ComparisonSnapshot } from "@/lib/comparison/types";

/** Public Matterport model that loads reliably in embeds (used for demo scans). */
const DEMO_MATTERPORT_MODEL = "https://my.matterport.com/show/?m=SxQL3iGyoDo";

/** Demo snapshot so the comparison UI is visible before real tours are uploaded. */
export function getDemoComparisonSnapshot(): ComparisonSnapshot {
  const scanA = {
    id: "demo-scan-a",
    project_id: "demo-project",
    name: "Level 8 — May Scan",
    matterport_url: DEMO_MATTERPORT_MODEL,
    capture_date: "2025-05-01",
    description: JSON.stringify({
      building: "Tower A",
      floor: "Level 8",
      engineer: "Raj Engineer",
      version: "v1.2",
      weather: "Clear",
      progressPercent: 50,
      notes: "Structure complete. MEP rough-in started on east wing.",
    }),
    thumbnail_url: null,
    sort_order: 0,
    created_at: "2025-05-01T00:00:00Z",
    updated_at: "2025-05-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
    deleted_by: null,
    metadata: {
      building: "Tower A",
      floor: "Level 8",
      engineer: "Raj Engineer",
      version: "v1.2",
      weather: "Clear",
      projectStage: "Active Construction",
      progressPercent: 50,
      notes: "Structure complete. MEP rough-in started on east wing.",
    },
    project: { id: "demo-project", name: "Green Heights Tower", client_name: "DM Creatives" },
  };

  const scanB = {
    ...scanA,
    id: "demo-scan-b",
    name: "Level 8 — June Scan",
    // Same public model — compares two visits of the same space (Scan B model was unavailable).
    matterport_url: DEMO_MATTERPORT_MODEL,
    capture_date: "2025-06-01",
    description: JSON.stringify({
      building: "Tower A",
      floor: "Level 8",
      engineer: "Raj Engineer",
      version: "v1.3",
      weather: "Partly Cloudy",
      progressPercent: 62,
      notes: "MEP 80% complete. Plastering started in living areas. Painting prep underway.",
    }),
    created_at: "2025-06-01T00:00:00Z",
    updated_at: "2025-06-01T00:00:00Z",
    metadata: {
      building: "Tower A",
      floor: "Level 8",
      engineer: "Raj Engineer",
      version: "v1.3",
      weather: "Partly Cloudy",
      projectStage: "Active Construction",
      progressPercent: 62,
      notes: "MEP 80% complete. Plastering started in living areas. Painting prep underway.",
    },
  };

  return {
    project: {
      id: "demo-project",
      name: "Green Heights Tower",
      client_id: "demo-client",
      client_name: "DM Creatives",
      location: "Mumbai, India",
      description: "Premium residential tower",
      status: "in_progress",
      start_date: "2024-06-01",
      completion_date: "2026-12-01",
      cover_image_url: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2025-06-01T00:00:00Z",
      created_by: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    scanA,
    scanB,
    dateWindowLabel: "May 10, 2025 → Jun 10, 2025",
    kpis: {
      previousProgress: 50,
      currentProgress: 62,
      difference: 12,
      scheduleStatus: "on_track",
      qualityStatus: "good",
      safetyStatus: "clear",
      healthScore: 87,
    },
    tradeProgress: [
      { trade: "Structure", status: "completed", delta: 8 },
      { trade: "Masonry", status: "completed", delta: 15 },
      { trade: "Plastering", status: "in_progress", detail: "60%", delta: 20 },
      { trade: "Electrical", status: "in_progress", detail: "80%", delta: 10 },
      { trade: "Plumbing", status: "in_progress", detail: "70%", delta: 5 },
      { trade: "Painting", status: "started", delta: 0 },
      { trade: "Flooring", status: "pending", delta: 0 },
    ],
    visualChanges: [
      { id: "completed", label: "Completed Work", count: 12, tone: "success" },
      { id: "new", label: "New Areas", count: 8, tone: "info" },
      { id: "pending", label: "Pending Areas", count: 15, tone: "warning" },
      { id: "delayed", label: "Delayed Work", count: 3, tone: "danger" },
      { id: "critical", label: "Critical Observations", count: 2, tone: "danger" },
    ],
    documentsBetween: [
      {
        id: "d1",
        project_id: "demo-project",
        folder_id: null,
        name: "Level 8 — Electrical Layout",
        category: "drawings",
        description: null,
        file_url: "#",
        file_name: "electrical.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-05-15T00:00:00Z",
        updated_at: "2025-05-15T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
    ],
    reportsBetween: [
      {
        id: "r1",
        project_id: "demo-project",
        title: "May Progress Report",
        report_type: "progress_report" as const,
        report_date: "2025-05-10",
        description: null,
        file_url: "#",
        file_name: "may-progress.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-05-10T00:00:00Z",
        updated_at: "2025-05-10T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: "r2",
        project_id: "demo-project",
        title: "June Progress Report",
        report_type: "progress_report" as const,
        report_date: "2025-06-10",
        description: null,
        file_url: "#",
        file_name: "june-progress.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-06-10T00:00:00Z",
        updated_at: "2025-06-10T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: "r3",
        project_id: "demo-project",
        title: "June Quality Report",
        report_type: "quality_report" as const,
        report_date: "2025-06-12",
        description: null,
        file_url: "#",
        file_name: "june-quality.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-06-12T00:00:00Z",
        updated_at: "2025-06-12T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: "r4",
        project_id: "demo-project",
        title: "June Safety Walk",
        report_type: "safety_report" as const,
        report_date: "2025-06-14",
        description: null,
        file_url: "#",
        file_name: "june-safety.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-06-14T00:00:00Z",
        updated_at: "2025-06-14T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
    ],
    newReports: [
      {
        id: "r2",
        project_id: "demo-project",
        title: "June Progress Report",
        report_type: "progress_report" as const,
        report_date: "2025-06-10",
        description: null,
        file_url: "#",
        file_name: "june-progress.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-06-10T00:00:00Z",
        updated_at: "2025-06-10T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: "r3",
        project_id: "demo-project",
        title: "June Quality Report",
        report_type: "quality_report" as const,
        report_date: "2025-06-12",
        description: null,
        file_url: "#",
        file_name: "june-quality.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-06-12T00:00:00Z",
        updated_at: "2025-06-12T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: "r4",
        project_id: "demo-project",
        title: "June Safety Walk",
        report_type: "safety_report" as const,
        report_date: "2025-06-14",
        description: null,
        file_url: "#",
        file_name: "june-safety.pdf",
        file_size: null,
        mime_type: "application/pdf",
        storage_path: null,
        created_at: "2025-06-14T00:00:00Z",
        updated_at: "2025-06-14T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
    ],
    resolvedIssues: [],
    newIssues: [
      {
        id: "demo-issue-new-1",
        project_id: "demo-project",
        title: "MEP clearance gap — East wing",
        description: "Ceiling void insufficient for duct routing.",
        priority: "high",
        status: "open",
        location: "Tower A, Level 8",
        assigned_to: null,
        due_date: "2025-06-15",
        resolved_at: null,
        created_at: "2025-06-05T00:00:00Z",
        updated_at: "2025-06-05T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
        issue_images: [],
      },
    ],
    pendingIssues: [
      {
        id: "demo-issue-pending-1",
        project_id: "demo-project",
        title: "Plastering touch-up — Corridor B",
        description: null,
        priority: "medium",
        status: "in_progress",
        location: "Tower A, Level 8",
        assigned_to: null,
        due_date: "2025-06-20",
        resolved_at: null,
        created_at: "2025-05-25T00:00:00Z",
        updated_at: "2025-06-01T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
        issue_images: [],
      },
    ],
    criticalIssues: [
      {
        id: "demo-issue-critical-1",
        project_id: "demo-project",
        title: "Rebar spacing deviation — Level 8",
        description: "Spacing exceeds tolerance at grid C4.",
        priority: "critical",
        status: "open",
        location: "Tower A, Level 8",
        assigned_to: null,
        due_date: "2025-06-10",
        resolved_at: null,
        created_at: "2025-05-28T00:00:00Z",
        updated_at: "2025-05-28T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
        issue_images: [],
      },
    ],
    timelineEvents: [
      {
        id: "te1",
        project_id: "demo-project",
        title: "MEP rough-in inspection",
        event_date: "2025-05-20",
        progress_note: "Electrical and plumbing rough-in signed off on east wing.",
        tour_id: null,
        report_id: null,
        sort_order: 0,
        created_at: "2025-05-20T00:00:00Z",
        updated_at: "2025-05-20T00:00:00Z",
        created_by: null,
        updated_by: null,
        deleted_at: null,
        deleted_by: null,
      },
    ],
    photosA: [
      { id: "pa1", url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&fit=crop", caption: "Living area — May", date: "2025-05-01" },
      { id: "pa2", url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=400&h=400&fit=crop", caption: "Corridor — May", date: "2025-05-01" },
      { id: "pa3", url: "https://images.unsplash.com/photo-1581094794329-cd811b68f2c8?w=400&h=400&fit=crop", caption: "Staircase — May", date: "2025-05-01" },
      { id: "pa4", url: "https://images.unsplash.com/photo-1590479773265-746b0a977868?w=400&h=400&fit=crop", caption: "Balcony — May", date: "2025-05-01" },
    ],
    photosB: [
      { id: "pb1", url: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&h=400&fit=crop", caption: "Living area — June", date: "2025-06-01" },
      { id: "pb2", url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=400&fit=crop", caption: "Corridor — June", date: "2025-06-01" },
      { id: "pb3", url: "https://images.unsplash.com/photo-1541976590-713941681591?w=400&h=400&fit=crop", caption: "Staircase — June", date: "2025-06-01" },
      { id: "pb4", url: "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=400&h=400&fit=crop", caption: "Balcony — June", date: "2025-06-01" },
    ],
    activities: [
      { id: "a1", type: "progress", label: "Plastering advanced to 60%", timestamp: "2025-06-01T10:00:00Z" },
      { id: "a2", type: "document", label: "Electrical layout uploaded", timestamp: "2025-05-15T14:00:00Z" },
    ],
    engineerNotesA: scanA.metadata.notes,
    engineerNotesB: scanB.metadata.notes,
    aiPlaceholder: {
      overallProgress:
        "Overall progress increased by 12% between site visits. MEP and plastering trades advanced significantly.",
      keyChanges: ["Masonry marked complete", "Plastering 60% complete", "+12% net progress gain"],
      pendingActivities: ["Painting", "Flooring", "False ceiling"],
      criticalRisks: ["Rebar spacing deviation — Level 8"],
      recommendedActions: [
        "Complete MEP inspection before ceiling closure",
        "Schedule quality walkthrough for plastering",
      ],
    },
  };
}

export const DEMO_PROJECTS_DATA = {
  projects: [
    {
      id: "demo-project",
      name: "Green Heights Tower",
      client_id: "demo-client",
      client_name: "DM Creatives",
      location: "Mumbai, India",
      description: null,
      status: "in_progress" as const,
      start_date: "2024-06-01",
      completion_date: "2026-12-01",
      cover_image_url: null,
      created_at: "2024-01-01T00:00:00Z",
      updated_at: "2025-06-01T00:00:00Z",
      created_by: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
  ],
  tours: [getDemoComparisonSnapshot().scanA, getDemoComparisonSnapshot().scanB],
};
